/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RelationshipsRouteImport } from './routes/relationships'
import { Route as PredictiveRouteImport } from './routes/predictive'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HeatmapRouteImport } from './routes/heatmap'
import { Route as FirRouteImport } from './routes/fir'
import { Route as DistrictRouteImport } from './routes/district'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationshipsRoute = RelationshipsRouteImport.update({
  id: '/relationships',
  path: '/relationships',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictiveRoute = PredictiveRouteImport.update({
  id: '/predictive',
  path: '/predictive',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatmapRoute = HeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const FirRoute = FirRouteImport.update({
  id: '/fir',
  path: '/fir',
  getParentRoute: () => rootRouteImport,
} as any)
const DistrictRoute = DistrictRouteImport.update({
  id: '/district',
  path: '/district',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/cases': typeof CasesRoute
  '/district': typeof DistrictRoute
  '/fir': typeof FirRoute
  '/heatmap': typeof HeatmapRoute
  '/login': typeof LoginRoute
  '/predictive': typeof PredictiveRoute
  '/relationships': typeof RelationshipsRoute
  '/reports': typeof ReportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/cases': typeof CasesRoute
  '/district': typeof DistrictRoute
  '/fir': typeof FirRoute
  '/heatmap': typeof HeatmapRoute
  '/login': typeof LoginRoute
  '/predictive': typeof PredictiveRoute
  '/relationships': typeof RelationshipsRoute
  '/reports': typeof ReportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/cases': typeof CasesRoute
  '/district': typeof DistrictRoute
  '/fir': typeof FirRoute
  '/heatmap': typeof HeatmapRoute
  '/login': typeof LoginRoute
  '/predictive': typeof PredictiveRoute
  '/relationships': typeof RelationshipsRoute
  '/reports': typeof ReportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alerts'
    | '/cases'
    | '/district'
    | '/fir'
    | '/heatmap'
    | '/login'
    | '/predictive'
    | '/relationships'
    | '/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/alerts'
    | '/cases'
    | '/district'
    | '/fir'
    | '/heatmap'
    | '/login'
    | '/predictive'
    | '/relationships'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alerts'
    | '/cases'
    | '/district'
    | '/fir'
    | '/heatmap'
    | '/login'
    | '/predictive'
    | '/relationships'
    | '/reports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AlertsRoute: typeof AlertsRoute
  CasesRoute: typeof CasesRoute
  DistrictRoute: typeof DistrictRoute
  FirRoute: typeof FirRoute
  HeatmapRoute: typeof HeatmapRoute
  LoginRoute: typeof LoginRoute
  PredictiveRoute: typeof PredictiveRoute
  RelationshipsRoute: typeof RelationshipsRoute
  ReportsRoute: typeof ReportsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relationships': {
      id: '/relationships'
      path: '/relationships'
      fullPath: '/relationships'
      preLoaderRoute: typeof RelationshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictive': {
      id: '/predictive'
      path: '/predictive'
      fullPath: '/predictive'
      preLoaderRoute: typeof PredictiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heatmap': {
      id: '/heatmap'
      path: '/heatmap'
      fullPath: '/heatmap'
      preLoaderRoute: typeof HeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fir': {
      id: '/fir'
      path: '/fir'
      fullPath: '/fir'
      preLoaderRoute: typeof FirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/district': {
      id: '/district'
      path: '/district'
      fullPath: '/district'
      preLoaderRoute: typeof DistrictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AlertsRoute: AlertsRoute,
  CasesRoute: CasesRoute,
  DistrictRoute: DistrictRoute,
  FirRoute: FirRoute,
  HeatmapRoute: HeatmapRoute,
  LoginRoute: LoginRoute,
  PredictiveRoute: PredictiveRoute,
  RelationshipsRoute: RelationshipsRoute,
  ReportsRoute: ReportsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
